# Key events exercise project.godot mappings, rather than the route driver's action names.
extends SceneTree
var failures := 0
var checks := 0
func _initialize() -> void: call_deferred("run")
func frames(count: int) -> void:
	for i in range(count):
		await physics_frame
		await process_frame
func key(code: Key, pressed: bool) -> void:
	var event := InputEventKey.new()
	event.keycode = code
	event.pressed = pressed
	Input.parse_input_event(event)
func check(ok: bool, label: String) -> void:
	checks += 1
	print("PASS " if ok else "FAIL ", label)
	if not ok: failures += 1
func run() -> void:
	var level = load("res://scenes/vertical_slice.tscn").instantiate()
	root.add_child(level)
	current_scene = level
	var player: SlicePlayer = level.get_node("Player")
	await frames(10)
	var start: float = player.position.x
	key(KEY_RIGHT, true)
	await frames(12)
	key(KEY_RIGHT, false)
	check(player.position.x > start + 10, "RIGHT key walks right")
	start = player.position.x
	key(KEY_LEFT, true)
	await frames(20)
	key(KEY_LEFT, false)
	check(player.position.x < start - 8, "LEFT key walks left")
	await frames(10)
	var pos := player.position
	key(KEY_UP, true)
	key(KEY_DOWN, true)
	await frames(4)
	check(Input.is_action_pressed("move_up") and Input.is_action_pressed("move_down") and player.position.distance_to(pos) < 1, "UP/DOWN stay mapped without vertical walking")
	key(KEY_UP, false)
	key(KEY_DOWN, false)
	key(KEY_Q, true)
	key(KEY_D, true)
	key(KEY_Z, true)
	key(KEY_S, true)
	await frames(2)
	check(not Input.is_action_pressed("move_left") and not Input.is_action_pressed("move_right") and not Input.is_action_pressed("move_up") and not Input.is_action_pressed("move_down"), "old Q/D/Z/S bindings removed")
	for code in [KEY_Q, KEY_D, KEY_Z, KEY_S]: key(code, false)
	key(KEY_SPACE, true)
	await frames(4)
	check(player.velocity.y < 0 and not player.is_on_floor(), "SPACE key jumps")
	key(KEY_SPACE, false)
	key(KEY_F, true)
	await frames(2)
	check(player.attack_time > 0, "F key attacks in air")
	await frames(23)
	check(player.attack_time > 0, "holding F starts another swing after recovery")
	key(KEY_F, false)
	await frames(22)
	check(player.attack_time == 0, "releasing F ends repeated attacks")
	key(KEY_E, true)
	await frames(2)
	check(Input.is_action_pressed("interact") and not level.gate.opened, "E maps to interaction and cannot pay remotely")
	key(KEY_E, false)
	key(KEY_G, true)
	key(KEY_A, true)
	key(KEY_R, true)
	await frames(2)
	check(Input.is_action_pressed("landing_attack") and Input.is_action_pressed("switch_equipment") and Input.is_action_pressed("special_attack"), "G/A/R have distinct production actions")
	var same_level = current_scene
	await frames(4)
	check(current_scene == same_level and not level.finished, "R does not restart or change the active level")
	key(KEY_G, false)
	key(KEY_A, false)
	key(KEY_R, false)
	player.position = Vector2(2040, 144)
	player.velocity = Vector2.ZERO
	level.gold = 12
	await frames(3)
	check(level.gate.player_near(), "player is inside the gate interaction area")
	key(KEY_ESCAPE, true)
	await frames(2)
	check(paused, "ESCAPE key pauses")
	key(KEY_E, true)
	await frames(3)
	check(paused and current_scene == level and not level.gate.opened, "E cannot activate gameplay while pause overlay is open")
	await frames(3)
	check(paused, "holding ESCAPE does not toggle pause twice")
	key(KEY_ESCAPE, false)
	await frames(2)
	key(KEY_ESCAPE, true)
	await frames(2)
	key(KEY_ESCAPE, false)
	check(not paused, "ESCAPE key resumes")
	await frames(3)
	check(not level.gate.opened and level.gold == 12, "paused E press is not reused at the gate after resume")
	key(KEY_E, false)
	await frames(2)
	key(KEY_E, true)
	await frames(3)
	check(level.gate.opened and level.gold == 0, "new E press opens gate once after resume")
	key(KEY_E, false)
	player.die()
	await frames(2)
	key(KEY_R, true)
	await frames(3)
	check(current_scene == level and player.dead, "R cannot restart after death")
	key(KEY_R, false)
	key(KEY_E, true)
	await frames(3)
	key(KEY_E, false)
	await frames(5)
	level = current_scene
	player = level.get_node("Player")
	check(not player.dead and player.health == 3 and player.position.x < 50, "E confirms restart on death overlay")
	level.gold = 12
	level.try_offering()
	level._on_exit(player)
	key(KEY_R, true)
	await frames(3)
	check(current_scene == level and level.finished, "R cannot restart on victory overlay")
	key(KEY_R, false)
	key(KEY_E, true)
	await frames(3)
	key(KEY_E, false)
	await frames(5)
	check(current_scene != level and not current_scene.finished, "E confirms replay on final victory overlay")
	level = current_scene
	level.queue_free()
	await frames(3)
	OS.delay_msec(300)
	print("RESULT ", checks, " keyboard checks; ", failures, " failures")
	quit(failures)
