"""Generate slimes, the gold coin and the HUD icons (RUN-013 harmonisation).

Usage: python3 tools/art/creatures.py [--preview DIR]

Outputs (assets/sprites/):
  enemy_slime_green.png   336x24  14 frames of 24x24 (0-7 patrol, 8-9 hit, 10-13 death), faces LEFT, ground contact on row 23, centred on col 12
  enemy_slime_purple.png  144x24  same layout, CORRUPT ramp, glowing core
  item_gold_coin.png      192x16  12 frames of 16x16, spinning coin centred on (8, 8)
  hud_icons.png           60x12   5 icons of 12x12: heart full, heart half, heart empty, coin, seal

Colours come only from tools/art/palette.py. Light comes from the upper left.
"""
import math
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from pixel import Canvas, grid, outline, save_png, sheet  # noqa: E402
import slime_art  # noqa: E402
import coin_art  # noqa: E402
from palette import BLOOD, CORRUPT, GOLD, OUTLINE, SLIME_GREEN, STONE  # noqa: E402

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(ROOT, "assets", "sprites")
BG = (52, 60, 66, 255)


# ---------------------------------------------------------------- slimes
# RUN-029: generated by slime_art.py (14 frames: patrol 8, hit 2, death 4).
def slime_sheet(ramp, tough):
	return slime_art.slime_sheet(ramp, tough)


# ------------------------------------------------------------------ coin
COIN_PAL = {"o": OUTLINE, "k": GOLD[0], "d": GOLD[1], "m": GOLD[2], "l": GOLD[3], "h": GOLD[4]}
COIN_FRONT = """
..oooooo..
.oldmmmmo.
olmmmmmmdo
olmmldmmdo
olmldddmdo
olmmdddmdo
omdmmdmmdo
odmmmmmmdo
.oddmmddo.
..oooooo..
"""
COIN_BACK = """
..oooooo..
.oldmmmmo.
olmmmmmmdo
olmmmmmmdo
olmmmmmmdo
olmmmmmmdo
omdmmmmddo
odmmmmmmdo
.oddmmddo.
..oooooo..
"""


def coin_frames():
	return coin_art.frames()


# ------------------------------------------------------------- HUD icons
HEART = """
.oooo.oooo.
ohhllolllmo
ohlllllllmo
ollllllllmo
ollllllmmdo
.olllmmmmdo
.ommmmmmdo.
..ommmmdo..
...ommdo...
....odo....
.....o.....
"""
HEART_LIVE = {"o": OUTLINE, "h": BLOOD[4], "l": BLOOD[3], "m": BLOOD[2], "d": BLOOD[1]}
HEART_DEAD = {"o": OUTLINE, "h": STONE[3], "l": STONE[2], "m": STONE[1], "d": STONE[0]}


def heart(live_cols, mono=False):
	f = Canvas(12, 12)
	rows = HEART.strip("\n").split("\n")
	for y, row in enumerate(rows):
		for x, ch in enumerate(row):
			if ch == ".":
				continue
			pal = HEART_LIVE if x < live_cols else HEART_DEAD
			f.put(x + 1, y, pal[ch])
	# a faint inner rim keeps empty sockets readable on dark HUD panels
	if live_cols < 11:
		for y, row in enumerate(rows):
			for x, ch in enumerate(row):
				if x >= live_cols and ch == "o":
					f.put(x + 1, y, STONE[3] if (x + y) % 1 == 0 and (y < 4 or x < 6) else STONE[2])
	return f


def hud_coin():
	f = Canvas(12, 12)
	f.blit(grid(COIN_FRONT, COIN_PAL), 1, 1)
	return f


def hud_seal():
	f = Canvas(12, 12)
	cx = cy = 5.5
	cells = set()
	for y in range(12):
		for x in range(12):
			dx, dy = x - cx, y - cy
			ang = math.atan2(dy, dx)
			if math.hypot(dx, dy) <= 4.7 + 0.35 * math.cos(10 * ang):
				cells.add((x, y))
	for (x, y) in cells:
		s = -(x - cx) * 0.5 - (y - cy) * 0.6
		f.put(x, y, GOLD[3 if s > 2.0 else 2 if s > -1.6 else 1])
	for (x, y) in [(3, 3), (5, 3), (6, 3), (8, 3)] + [(x, 4) for x in range(3, 9)]:
		f.put(x, y, GOLD[0])
	for x in range(3, 9):
		f.put(x, 5, GOLD[1])
		f.put(x, 6, GOLD[0])
	f.put(4, 4, GOLD[1])
	f.put(7, 4, GOLD[1])
	f.put(3, 2, GOLD[4]); f.put(4, 2, GOLD[4])
	return outline(f, OUTLINE)


def hud_sheet():
	return sheet([heart(11), heart(5), heart(0), hud_coin(), hud_seal()], 5)


# ------------------------------------------------------------------ main
def main():
	preview = None
	if "--preview" in sys.argv:
		preview = sys.argv[sys.argv.index("--preview") + 1]
		os.makedirs(preview, exist_ok=True)
	os.makedirs(OUT, exist_ok=True)
	outputs = {
		"enemy_slime_green.png": slime_sheet(SLIME_GREEN, False),
		"enemy_slime_purple.png": slime_sheet(CORRUPT, True),
		"item_gold_coin.png": sheet(coin_frames(), 12),
		"hud_icons.png": hud_sheet(),
	}
	for name, canvas in outputs.items():
		save_png(canvas, os.path.join(OUT, name))
		print(name, canvas.w, canvas.h)
		if preview:
			save_png(canvas, os.path.join(preview, name[:-4] + "_x8.png"), 8, BG)


if __name__ == "__main__":
	main()
