class_name SlicePlayer
extends CharacterBody2D
enum MotionState { GROUND, AIR, WALL_SLIDE, DEAD }

signal health_changed(value: float, maximum: float)
signal died
signal equipment_changed(slot: int)
signal projectile_fired(arrow: Node2D)
const ARROW_SCRIPT = preload("res://scripts/arrow.gd")
const BOW_INTERVAL = 1.5
enum DamageSource { CONTACT_MELEE, PROJECTILE, SOLID_TRAP, FLAME, SWARM, VOID }
const SPEED = 105.0
const GRAVITY = 760.0
const JUMP_SPEED = -255.0
const DOUBLE_JUMP_SPEED = -225.0
const WALL_SLIDE_SPEED = 35.0
const WALL_JUMP_SPEED = 110.0
const GRIPPABLE_MASK = 8
const SWORD_DAMAGE = 0.5
# RANGE 1 = 24 px (1.5 terrain blocks), measured from the hand to the tip.
const SWORD_RANGE = 24.0
const ATTACK_INTERVAL = 1.0
const ATTACK_DURATION = 0.28
# Keep the original windup, contact and recovery proportions as the cycle changes.
const ATTACK_HIT_START_TIME = ATTACK_DURATION * (0.25 / 0.32)
const ATTACK_HIT_END_TIME = ATTACK_DURATION * (0.11 / 0.32)
const INVULNERABILITY_DURATION = 1.20
const HURT_FLASH_DURATION = 0.10
const HIT_STUN_DURATION = 0.18
const KNOCKBACK_DURATION = 0.16
# Pixel art generated by tools/art/knight.py: the sword is drawn in every knight frame
# and, during the contact window, at the exact gameplay blade angle.
const SPARK_TEXTURE = preload("res://assets/sprites/vfx_hit_spark.png")
const PUFF_TEXTURE = preload("res://assets/sprites/vfx_air_puff.png")
const DUST_TEXTURE = preload("res://assets/sprites/vfx_wall_dust.png")
const LAND_DUST_TEXTURE = preload("res://assets/sprites/vfx_land_dust.png")
const SPARK_DURATION = 0.2
# Visual sword chain: consecutive hits cycle through three moves (atk1..atk3).
# Damage, cadence and contact window stay those of the single Sword hit above.
const CHAIN_MOVES = 3
const CHAIN_GRACE = 0.25
# Gesture frame boundaries (fraction of ATTACK_DURATION) and chain frames (seconds) while F is held.
# g0-g1 windup, g2-g4 contact window (blade at the gameplay angle), g5 follow-through.
const GESTURE_STEPS = [0.11, 1.0 - ATTACK_HIT_START_TIME / ATTACK_DURATION, 0.365, 0.51, 1.0 - ATTACK_HIT_END_TIME / ATTACK_DURATION]
const CHAIN_STEPS = [0.45, 0.62, 0.82]
# Hip height of base_run frames relative to the layered upper-body frames.
const RUN_HIP_OFFSET = [0, 1, 0, -1, 0, 1, 0, -1]
const LAND_DURATION = 0.1
const LAND_SPEED = 160.0
const LAND_DUST_DURATION = 0.24
var max_health_units: int = 30
var health_units: int = 30
var health: float:
	get: return HealthUnits.to_hp(health_units)
var max_health: float:
	get: return HealthUnits.to_hp(max_health_units)
var facing: int = 1
var attack_facing: int = 1
var dead: bool = false
var controls_enabled: bool = true
# Presentation only: the level owns timing and the one-time new-game policy.
var resurrection_active: bool = false
var resurrection_progress: float = 0.0
var coyote: float = 0.0
var jump_buffer: float = 0.0
var invulnerability: float = 0.0
var hurt_flash_time: float = 0.0
var knockback_time: float = 0.0
var hit_stun_time: float = 0.0
var attack_time: float = 0.0
var attack_cooldown: float = 0.0
var bow_cooldown: float = 0.0
var shot_age: float = 99.0
var equipment: Dictionary = {"melee": "Sword0", "ranged": ""}
var has_longbow: bool = false
var active_slot: int = 0
var hit_targets: Array[int] = []
var can_double_jump: bool = false
var wall_jump_lockout: bool = false
var jump_flash: float = 0.0
var jump_effect_origin := Vector2.ZERO
var motion_state: MotionState = MotionState.AIR
var wall_normal: float = 0.0
var blocked_wall_normal: float = 0.0
var wall_detach_time: float = 0.0
var wall_control_time: float = 0.0
var attack_cancelled: bool = false
# Impact sparks in world space: [position, age]. Purely visual.
var hit_sparks: Array = []
# Visual-only state: chain move, time since the last swing start, landing squash.
var chain_move: int = 0
var since_swing: float = 99.0
var land_time: float = 0.0
var land_dusts: Array = []
var was_on_floor: bool = true
@onready var sprite: AnimatedSprite2D = $Sprite
@onready var upper: AnimatedSprite2D = $Sprite/Upper
@onready var sword: Area2D = $AttackArea
@onready var hurt_material: ShaderMaterial = sprite.material
# RUN-016 presentation (Claude): Longbow animations, release puff and equipment sounds.
const SHOT_RELEASE_TIME = 4.0 / 12.0
const SHOT_DRAW_WINDOW = 0.45
const RELEASE_FX = preload("res://assets/sprites/vfx_arrow_release.png")
const BOW_SHOT_SFX = preload("res://assets/sounds/sfx_weapon_bow_shot.tres")
const WEAPON_SWITCH_SFX = preload("res://assets/sounds/sfx_weapon_switch.wav")
const WEAPON_EQUIP_SFX = preload("res://assets/sounds/sfx_weapon_equip.wav")
var _fx_slot: int = 0
var _fx_owned: bool = false
var _equipment_sound: AudioStreamPlayer
var _fx_armed: bool = false  # level setup (configure_equipment on spawn) stays silent
# RUN-018 presentation (Claude): the knight frames come without the weapon (body / mid / over
# layers, tools/art/run018/knight_armed.py); the active melee weapon and its smear are drawn
# between them at the exact gameplay reach (WeaponArt), Throwing Knives have their own stance.
const RIG = preload("res://assets/run018/knight/knight_rig.gd")
const KNIFE_TEXTURE = preload("res://assets/run018/world/proj_knife.png")
const KNIFE_RELEASE_FX = preload("res://assets/run018/world/vfx_knife_release.png")
const KNIFE_THROW_SFX = preload("res://assets/sounds/run018/sfx_weapon_knives_throw.tres")
const LIGHT_SWING_SFX = preload("res://assets/sounds/sfx_melee_swing_light.tres")
const HEAVY_SWING_SFX = preload("res://assets/sounds/run018/sfx_melee_swing_heavy.tres")
const HEAVY_SWINGS := ["Longsword", "DarkScythe", "Warhammer", "Halberds"]
const KILL_HEAL_MINOR = preload("res://assets/run018/world/vfx_heal_kill_minor.png")
const KILL_HEAL_MAJOR = preload("res://assets/run018/world/vfx_heal_kill_major.png")
const KILL_HEAL_SFX = preload("res://assets/sounds/run018/sfx_heal_kill.wav")
@onready var _smear: Sprite2D = $Sprite/Smear
@onready var _mid: AnimatedSprite2D = $Sprite/Mid
@onready var _weapon: Sprite2D = $Sprite/Weapon
@onready var _over: AnimatedSprite2D = $Sprite/Over

func _ready() -> void:
	# Each player owns its blade resource: upgrades must not alter other instances.
	$AttackArea/Shape.shape = $AttackArea/Shape.shape.duplicate()
	_update_melee_shape()
	_equipment_sound = AudioStreamPlayer.new()
	_equipment_sound.bus = &"SFX"
	_equipment_sound.volume_db = -6.0
	add_child(_equipment_sound)
	projectile_fired.connect(_on_projectile_fired_fx)
	equipment_changed.connect(_on_equipment_changed_fx)
	set_deferred("_fx_armed", true)
	for carrier in [sprite, upper]:
		carrier.frame_changed.connect(_sync_weapon_layers)
		carrier.animation_changed.connect(_sync_weapon_layers)
	_connect_kill_heal.call_deferred()
	_sync_weapon_layers()

func _process(_delta: float) -> void:
	_sync_weapon_layers()

func _knives() -> bool:
	return str(equipment.ranged).begins_with("ThrowingKnives")

# Ranged animation names: Longbow keeps bow_* / shoot, Throwing Knives use knife_* / throw.
func _ranged_anim(name: String) -> StringName:
	if not _knives(): return StringName(name)
	match name:
		"shoot": return &"throw"
		"up_shoot": return &"up_throw"
	return StringName(name.replace("bow_", "knife_"))

# Mirror the carrier frame (Upper when layered) on mid/over and draw the weapon and smear between.
func _sync_weapon_layers() -> void:
	if _mid == null: return
	var carrier: AnimatedSprite2D = upper if upper.visible else sprite
	var anim: StringName = carrier.animation
	var frame: int = carrier.frame
	var offset: Vector2 = upper.position if carrier == upper else Vector2.ZERO
	for layer: AnimatedSprite2D in [_mid, _over]:
		layer.flip_h = carrier.flip_h
		layer.position = offset
		if layer.sprite_frames.has_animation(anim):
			if layer.animation != anim: layer.animation = anim
			layer.frame = frame
			layer.show()
		else:
			layer.hide()
	var frames: Array = RIG.FRAMES.get(String(anim), [])
	var spec: Array = frames[frame] if frame < frames.size() else [0]
	var kind: int = spec[0]
	var held := {}
	var swept := {}
	var stats := WeaponCatalog.stats(equipment.melee)
	if kind != 0 and not stats.is_empty():
		var base := str(equipment.melee).left(-1)
		var hand := Vector2(spec[1], spec[2])
		if kind == 3:
			var stow: Array = WeaponArt.STOWED[base]
			held = WeaponArt.held(stow[0], hand, spec[3] if stow[2] == null else stow[2], stow[1])
		else:
			held = WeaponArt.held(base, hand, spec[4] if base in WeaponArt.POLES else spec[3], stats.reach)
			var smear: Array = spec[5]
			if kind == 1 and not smear.is_empty():
				swept = WeaponArt.smear(hand, smear[0], smear[1], smear[2], stats.reach)
	# Like the authored frames, nothing is drawn under the feet line while standing on the ground.
	var clip := is_on_floor() or dead or resurrection_active
	_place(_weapon, held, offset, carrier.flip_h, clip)
	_place(_smear, swept, offset, carrier.flip_h, clip)

func _place(node: Sprite2D, art: Dictionary, offset: Vector2, flip: bool, clip: bool) -> void:
	if art.is_empty():
		node.hide()
		return
	var texture: Texture2D = art.texture
	var origin: Vector2i = art.origin
	var size := texture.get_size()
	# Rig coordinates are the player's; the sprite sits 29 px above the feet.
	var rows := size.y
	if clip: rows = clampf(-(origin.y + offset.y), 0.0, size.y)
	if rows <= 0.0:
		node.hide()
		return
	node.texture = texture
	node.region_rect = Rect2(0, 0, size.x, rows)
	node.flip_h = flip
	node.position = Vector2(-(origin.x + size.x) if flip else origin.x, origin.y + 29.0) + offset
	node.show()

func _connect_kill_heal() -> void:
	var node := get_parent()
	while node != null and not node.has_signal("kill_healed"): node = node.get_parent()
	if node != null and not node.is_connected("kill_healed", _on_kill_healed):
		node.connect("kill_healed", _on_kill_healed)

# Instant heal from a kill: a short feedback on the knight, never a pickup.
func _on_kill_healed(amount: float) -> void:
	if dead or not is_inside_tree(): return
	var strip: Texture2D = KILL_HEAL_MAJOR if amount >= 1.0 else KILL_HEAL_MINOR
	OneShotFx.spawn(self, strip, Vector2i(24, 32), 12.0, global_position + Vector2(0, 1), false, Vector2(0.5, 1.0), KILL_HEAL_SFX, -4.0)

func _on_projectile_fired_fx(arrow: Node2D) -> void:
	var world := get_parent()
	var at := arrow.global_position - Vector2(4.0 * facing, 0.0)
	# The look is captured from the weapon that fired: a later swap never restyles a flying shot.
	var knife := _knives()
	if knife and arrow.has_method("set_look"): arrow.set_look("knife")
	OneShotFx.spawn(world, KNIFE_RELEASE_FX if knife else RELEASE_FX, Vector2i(16, 12), 24.0, at, facing < 0, Vector2(0.0, 0.5), KNIFE_THROW_SFX if knife else BOW_SHOT_SFX, -8.0)

# Acquisition plays the equip cue; a slot change by the player plays the switch cue.
func _on_equipment_changed_fx(slot: int) -> void:
	var cue: AudioStream = null
	if not _fx_armed:
		pass
	elif has_longbow and not _fx_owned:
		cue = WEAPON_EQUIP_SFX
	elif slot != _fx_slot:
		cue = WEAPON_SWITCH_SFX
	_fx_slot = slot
	_fx_owned = has_longbow
	$SwingSound.stream = HEAVY_SWING_SFX if str(equipment.melee).left(-1) in HEAVY_SWINGS else LIGHT_SWING_SFX
	_sync_weapon_layers()
	if cue != null and _equipment_sound != null and is_inside_tree():
		_equipment_sound.stream = cue
		_equipment_sound.play()

func _physics_process(delta: float) -> void:
	if resurrection_active:
		_update_resurrection_visuals()
		return
	attack_cooldown = maxf(0.0, attack_cooldown - delta)
	bow_cooldown = maxf(0.0, bow_cooldown - delta)
	invulnerability = maxf(0.0, invulnerability - delta)
	hurt_flash_time = maxf(0.0, hurt_flash_time - delta)
	# Remove countdown roundoff at the exact expiration tick.
	if invulnerability < 0.000001: invulnerability = 0.0
	if hurt_flash_time < 0.000001: hurt_flash_time = 0.0
	knockback_time = maxf(0.0, knockback_time - delta)
	hit_stun_time = maxf(0.0, hit_stun_time - delta)
	jump_flash = maxf(0.0, jump_flash - delta)
	wall_detach_time = maxf(0.0, wall_detach_time - delta)
	wall_control_time = maxf(0.0, wall_control_time - delta)
	since_swing += delta
	shot_age += delta
	land_time = maxf(0.0, land_time - delta)
	velocity.y = minf(velocity.y + GRAVITY * delta, 420.0)
	if dead:
		motion_state = MotionState.DEAD
		velocity.x = move_toward(velocity.x, 0.0, 600.0 * delta)
		_age_sparks(delta)
		upper.hide()
		move_and_slide()
		queue_redraw()
		return
	if is_on_floor() and velocity.y >= 0.0:
		coyote = 0.10
		can_double_jump = false
		wall_jump_lockout = false
	else:
		coyote = maxf(0.0, coyote - delta)
	jump_buffer = maxf(0.0, jump_buffer - delta)
	var direction: float = Input.get_axis("move_left", "move_right") if controls_enabled else 0.0
	_update_wall_state(direction)
	if controls_enabled and knockback_time <= 0.0 and Input.is_action_just_pressed("jump"):
		jump_buffer = 0.12
	if knockback_time <= 0.0 and jump_buffer > 0.0 and coyote > 0.0:
		velocity.y = JUMP_SPEED
		jump_buffer = 0.0
		coyote = 0.0
		can_double_jump = true
		$JumpSound.play()
	elif knockback_time <= 0.0 and jump_buffer > 0.0 and wall_normal != 0.0 and not is_on_floor():
		velocity = Vector2(wall_normal * WALL_JUMP_SPEED, JUMP_SPEED)
		facing = int(wall_normal)
		blocked_wall_normal = wall_normal
		wall_control_time = 0.07
		wall_detach_time = 0.20
		wall_jump_lockout = true
		can_double_jump = false
		coyote = 0.0
		jump_buffer = 0.0
		motion_state = MotionState.AIR
		$WallJumpSound.play()
	elif knockback_time <= 0.0 and jump_buffer > 0.0 and can_double_jump and not wall_jump_lockout:
		velocity.y = DOUBLE_JUMP_SPEED
		jump_buffer = 0.0
		can_double_jump = false
		jump_flash = 0.22
		jump_effect_origin = global_position
		$DoubleJumpSound.play()
	if controls_enabled and knockback_time <= 0.0 and Input.is_action_just_released("jump") and not Input.is_action_pressed("jump") and velocity.y < -90.0:
		velocity.y *= 0.45
	if motion_state == MotionState.WALL_SLIDE:
		velocity.y = minf(velocity.y, WALL_SLIDE_SPEED)
	if direction != 0.0 and wall_control_time <= 0.0 and (attack_time >= ATTACK_HIT_START_TIME or attack_time <= ATTACK_HIT_END_TIME):
		facing = 1 if direction > 0.0 else -1
		if attack_time >= ATTACK_HIT_START_TIME or attack_time <= 0.0:
			attack_facing = facing
	if knockback_time <= 0.0 and wall_control_time <= 0.0:
		velocity.x = move_toward(velocity.x, direction * SPEED, 2100.0 * delta)
	if controls_enabled and hit_stun_time <= 0.0 and has_longbow and Input.is_action_just_pressed("switch_equipment"):
		active_slot = 1 - active_slot
		attack_time = 0.0
		attack_cancelled = true
		equipment_changed.emit(active_slot)
	if active_slot == 1 and controls_enabled and hit_stun_time <= 0.0 and Input.is_action_pressed("attack") and bow_cooldown <= 0.000001:
		_fire_arrow()
	if active_slot == 0 and controls_enabled and hit_stun_time <= 0.0 and Input.is_action_pressed("attack") and attack_time <= 0.0 and attack_cooldown <= 0.000001 and motion_state != MotionState.WALL_SLIDE:
		attack_time = ATTACK_DURATION
		attack_cooldown = WeaponCatalog.stats(equipment.melee).interval
		attack_facing = facing
		attack_cancelled = false
		hit_targets.clear()
		chain_move = (chain_move + 1) % CHAIN_MOVES if since_swing <= WeaponCatalog.stats(equipment.melee).interval + CHAIN_GRACE else 0
		since_swing = 0.0
		$SwingSound.play()
	attack_time = maxf(0.0, attack_time - delta)
	if attack_cancelled:
		since_swing = 99.0
	_update_damage_visuals()
	_update_animation()
	_age_sparks(delta)
	var fall_speed := velocity.y
	move_and_slide()
	_update_wall_state(direction)
	_update_landing(fall_speed)
	_update_sword()
	_sync_weapon_layers()
	queue_redraw()

func set_resurrection_progress(value: float) -> void:
	if not resurrection_active:
		_rest_on_floor()
	resurrection_active = true
	resurrection_progress = clampf(value, 0.0, 1.0)
	controls_enabled = false
	attack_time = 0.0
	attack_cancelled = true
	velocity = Vector2.ZERO
	_update_resurrection_visuals()

# The authored spawn sits 4 px above the ground and gravity is suspended during the presentation:
# settle the body first so the lying pose, the rise and idle share the floor line (no drop or
# camera jump when controls return). Only within a short probe, never through a void.
func _rest_on_floor() -> void:
	var hit := move_and_collide(Vector2(0, 8), true)
	if hit != null: position += hit.get_travel()
	velocity = Vector2.ZERO
	move_and_slide()  # refresh the floor contact: idle, not one fall frame, when physics resumes

func finish_resurrection() -> void:
	resurrection_active = false
	resurrection_progress = 1.0
	upper.hide()
	sprite.play("idle")
	# The level restores controls after its cinematic/modal locks have finished.

func _update_resurrection_visuals() -> void:
	upper.hide()
	var animation_name: StringName = &"resurrect"
	var frames := sprite.sprite_frames
	var dedicated := frames.has_animation(animation_name)
	if not dedicated:
		# Technical placeholder until Claude supplies a dedicated resurrection strip.
		animation_name = &"dead"
	var frame_count := frames.get_frame_count(animation_name)
	var sampled := mini(frame_count - 1, int(resurrection_progress * frame_count))
	sprite.animation = animation_name
	sprite.pause()
	sprite.set_frame_and_progress(sampled if dedicated else frame_count - 1 - sampled, 0.0)

func prepare_dialogue_pose() -> void:
	controls_enabled = false
	velocity = Vector2.ZERO
	attack_time = 0.0
	attack_cancelled = true
	upper.hide()
	sprite.play("idle")
	# Only presentation advances while the level pauses gameplay physics.
	sprite.process_mode = Node.PROCESS_MODE_ALWAYS

func finish_dialogue_pose() -> void:
	# Restore the authored inherited mode; subsequent menu pauses freeze the knight again.
	sprite.process_mode = Node.PROCESS_MODE_INHERIT

func configure_equipment(ranged_owned: bool) -> void:
	configure_loadout({"melee": "Sword0", "ranged": "Longbow0" if ranged_owned else ""})

func active_item() -> String:
	return str(equipment.ranged if active_slot == 1 else equipment.melee)

func configure_loadout(slots: Dictionary) -> void:
	var melee := str(slots.get("melee", "Sword0"))
	var ranged := str(slots.get("ranged", ""))
	if not WeaponCatalog.valid(melee, "melee") or (not ranged.is_empty() and not WeaponCatalog.valid(ranged, "ranged")):
		return
	var replaced: bool = equipment.melee != melee or equipment.ranged != ranged
	equipment = {"melee": melee, "ranged": ranged}
	has_longbow = not ranged.is_empty()
	if not has_longbow:
		active_slot = 0
	if replaced:
		shot_age = 99.0
		# Slot timers survive acquisition/replacement; cancel any previous weapon's swing.
		attack_time = 0.0
		attack_cancelled = true
	if is_node_ready():
		_update_melee_shape()
	equipment_changed.emit(active_slot)

func _update_melee_shape() -> void:
	var shape: RectangleShape2D = $AttackArea/Shape.shape
	shape.size = Vector2(WeaponCatalog.stats(equipment.melee).reach, 4.0)

func _fire_arrow() -> void:
	if resurrection_active:
		return
	var stats := WeaponCatalog.stats(equipment.ranged if has_longbow else "Longbow0")
	bow_cooldown = stats.interval
	shot_age = 0.0
	var arrow: Node2D = ARROW_SCRIPT.new()
	# Keep ownership under the player for scene restart, but flight in world space.
	arrow.process_mode = Node.PROCESS_MODE_PAUSABLE
	add_child(arrow)
	arrow.top_level = true
	arrow.global_position = global_position + Vector2(4.0 * facing, -10.0)
	arrow.setup(facing, stats.damage, stats.reach)
	projectile_fired.emit(arrow)

func _update_wall_state(direction: float) -> void:
	wall_normal = 0.0
	if is_on_floor() and velocity.y >= 0.0:
		motion_state = MotionState.GROUND
		return
	# Two probes cover the straight sides of the capsule, not its rounded feet.
	for side in [-1.0, 1.0]:
		if wall_detach_time > 0.0 and -side == blocked_wall_normal:
			continue
		for height in [-6.0, -12.0]:
			var from := global_position + Vector2(0, height)
			var query := PhysicsRayQueryParameters2D.create(from, from + Vector2(side * 5.5, 0), GRIPPABLE_MASK)
			var hit := get_world_2d().direct_space_state.intersect_ray(query)
			if not hit.is_empty() and absf(hit.normal.x) > 0.9:
				wall_normal = hit.normal.x
				break
		if wall_normal != 0.0:
			break
	if wall_normal != 0.0 and velocity.y >= 0.0 and direction != wall_normal and knockback_time <= 0.0:
		motion_state = MotionState.WALL_SLIDE
		velocity.y = minf(velocity.y, WALL_SLIDE_SPEED)
		if attack_time > 0.0:
			attack_cancelled = true
	else:
		motion_state = MotionState.AIR

func take_damage(amount: float, impulse: Vector2 = Vector2.ZERO, source: int = DamageSource.CONTACT_MELEE) -> void:
	if dead or resurrection_active:
		return
	if source == DamageSource.VOID:
		die()
		return
	if invulnerability > 0.0 or amount <= 0.0:
		return
	health_units = maxi(0, health_units - HealthUnits.from_hp(amount))
	if health_units == 0:
		die()
		return
	$HurtSound.play()
	health_changed.emit(health, max_health)
	invulnerability = INVULNERABILITY_DURATION
	hurt_flash_time = HURT_FLASH_DURATION
	var has_knockback: bool = source == DamageSource.CONTACT_MELEE or source == DamageSource.SOLID_TRAP or source == DamageSource.FLAME
	var interrupts_attack: bool = source == DamageSource.CONTACT_MELEE or source == DamageSource.PROJECTILE
	if source == DamageSource.CONTACT_MELEE:
		hit_stun_time = HIT_STUN_DURATION
	if interrupts_attack:
		attack_time = 0.0
		attack_cancelled = true
	if has_knockback:
		knockback_time = KNOCKBACK_DURATION
		jump_buffer = 0.0
		wall_control_time = 0.0
		velocity = impulse
	_update_damage_visuals()

func _update_damage_visuals() -> void:
	hurt_material.set_shader_parameter("white_flash", 1.0 if hurt_flash_time > 0.0 and not dead else 0.0)
	sprite.modulate = Color.WHITE
	if not dead and hurt_flash_time <= 0.0 and invulnerability > 0.0:
		var blink_elapsed := maxf(0.0, INVULNERABILITY_DURATION - invulnerability - HURT_FLASH_DURATION)
		sprite.modulate.a = 0.25 if int(blink_elapsed * 10.0) % 2 == 0 else 1.0

func heal(amount: float) -> float:
	if dead or amount <= 0.0:
		return 0.0
	var before := health_units
	health_units = mini(max_health_units, health_units + HealthUnits.from_hp(amount))
	if health_units != before:
		health_changed.emit(health, max_health)
	return HealthUnits.to_hp(health_units - before)

func die() -> void:
	if dead or resurrection_active:
		return
	dead = true
	for child in get_children():
		if child.get_script() == ARROW_SCRIPT:
			child.queue_free()
	motion_state = MotionState.DEAD
	health_units = 0
	attack_time = 0.0
	hit_stun_time = 0.0
	knockback_time = 0.0
	hurt_flash_time = 0.0
	_update_damage_visuals()
	# The level pauses on death; the collapse keeps playing under the death overlay.
	sprite.process_mode = Node.PROCESS_MODE_ALWAYS
	upper.hide()
	sprite.flip_h = facing < 0
	sprite.play("dead")
	# DeathSound keeps playing while the level pauses for the death transition.
	$DeathSound.play()
	health_changed.emit(0.0, max_health)
	died.emit()
	queue_redraw()

func _update_sword() -> void:
	if resurrection_active:
		return
	var angle: float = lerpf(-1.5, 1.2, 1.0 - attack_time / ATTACK_DURATION)
	var blade_direction := Vector2(cos(angle) * attack_facing, sin(angle))
	var hand := Vector2(4.0 * attack_facing, -10.0)
	sword.position = hand + blade_direction * (WeaponCatalog.stats(equipment.melee).reach * 0.5)
	sword.rotation = blade_direction.angle()
	if attack_cancelled or dead or attack_time >= ATTACK_HIT_START_TIME or attack_time <= ATTACK_HIT_END_TIME:
		return
	var query := PhysicsShapeQueryParameters2D.new()
	query.shape = $AttackArea/Shape.shape
	query.transform = sword.global_transform
	query.collision_mask = 4
	for hit in get_world_2d().direct_space_state.intersect_shape(query):
		var body = hit.collider
		if not body.has_method("take_damage") or hit_targets.has(body.get_instance_id()):
			continue
		var ray := PhysicsRayQueryParameters2D.create(to_global(hand), body.global_position + Vector2(0, -6), 1)
		if not get_world_2d().direct_space_state.intersect_ray(ray).is_empty():
			continue
		hit_targets.append(body.get_instance_id())
		body.take_damage(WeaponCatalog.stats(equipment.melee).damage, Vector2(attack_facing * 60.0, -55.0))
		hit_sparks.append([body.global_position + Vector2(-attack_facing * 4.0, -7.0), 0.0])

func _update_animation() -> void:
	if resurrection_active:
		_update_resurrection_visuals()
		return
	upper.hide()
	upper.position = Vector2.ZERO
	sprite.flip_h = facing < 0
	if knockback_time > 0.0 or hit_stun_time > 0.0:
		sprite.play(_ranged_anim("bow_hurt") if active_slot == 1 and has_longbow else &"hurt")
		return
	if active_slot == 1 and has_longbow:
		_update_bow_animation()
		return
	var chain_time := _chain_time()
	if chain_time >= 0.0:
		_show_attack(chain_time)
	elif motion_state == MotionState.WALL_SLIDE:
		# Face the wall: the far hand grips it while the near foot brakes.
		sprite.flip_h = wall_normal > 0.0
		sprite.play("wall")
	elif not is_on_floor():
		sprite.play("rise" if velocity.y < 0.0 else "fall")
	elif land_time > 0.0:
		sprite.play("land")
	else:
		_play_synced("run" if absf(velocity.x) > 5.0 else "idle")

# Longbow active: release/draw frames from the bow cooldown, otherwise bow locomotion.
func _update_bow_animation() -> void:
	var shot := _shot_frame()
	if shot >= 0:
		sprite.flip_h = facing < 0
		if is_on_floor() and absf(velocity.x) <= 5.0 and motion_state != MotionState.WALL_SLIDE:
			sprite.animation = _ranged_anim("shoot")
			sprite.frame = shot
			return
		upper.show()
		upper.flip_h = sprite.flip_h
		upper.animation = _ranged_anim("up_shoot")
		upper.frame = shot
		if is_on_floor():
			_play_synced("base_run")
			upper.position.y = RUN_HIP_OFFSET[sprite.frame % RUN_HIP_OFFSET.size()]
		else:
			sprite.play("base_rise" if velocity.y < 0.0 else "base_fall")
	elif motion_state == MotionState.WALL_SLIDE:
		sprite.flip_h = wall_normal > 0.0
		sprite.play(_ranged_anim("bow_wall"))
	elif not is_on_floor():
		sprite.play(_ranged_anim("bow_rise" if velocity.y < 0.0 else "bow_fall"))
	elif land_time > 0.0:
		sprite.play(_ranged_anim("bow_land"))
	else:
		_play_synced(_ranged_anim("bow_run" if absf(velocity.x) > 5.0 else "bow_idle"))

# 0-3: release just after a shot; 4-6: nock and draw while F is held before the next one.
func _shot_frame() -> int:
	if dead:
		return -1
	# Presentation tracks the actual shot; a changed interval cannot replay an old release.
	if bow_cooldown > 0.0 and shot_age < SHOT_RELEASE_TIME:
		return mini(3, int(shot_age * 12.0))
	var holding: bool = controls_enabled and hit_stun_time <= 0.0 and Input.is_action_pressed("attack")
	if holding and bow_cooldown > 0.0 and bow_cooldown < SHOT_DRAW_WINDOW:
		return 4 + mini(2, int((SHOT_DRAW_WINDOW - bow_cooldown) / (SHOT_DRAW_WINDOW / 3.0)))
	return -1

# Seconds since the current swing started while its gesture plays or F keeps the chain going.
func _chain_time() -> float:
	if attack_cancelled or dead or active_slot != 0:
		return -1.0
	if attack_time > 0.0:
		return ATTACK_DURATION - attack_time
	var holding: bool = controls_enabled and Input.is_action_pressed("attack") and hit_stun_time <= 0.0
	if holding and since_swing < WeaponCatalog.stats(equipment.melee).interval + CHAIN_GRACE and motion_state != MotionState.WALL_SLIDE:
		return since_swing
	return -1.0

func _attack_frame(elapsed: float) -> int:
	var frame := 0
	if elapsed < ATTACK_DURATION:
		var progress := elapsed / ATTACK_DURATION
		for step in GESTURE_STEPS:
			if progress >= step: frame += 1
		return frame
	frame = 6
	for step in CHAIN_STEPS:
		if elapsed >= step: frame += 1
	return frame

func _show_attack(elapsed: float) -> void:
	var frame := _attack_frame(elapsed)
	var move := chain_move + 1
	# The blade stays on the side it strikes until the gesture ends.
	sprite.flip_h = (attack_facing if attack_time > 0.0 else facing) < 0
	if is_on_floor() and absf(velocity.x) <= 5.0:
		sprite.animation = "atk%d" % move
		sprite.frame = frame
		return
	# Moving or airborne: legs and cape keep their own cycle under the upper body.
	upper.show()
	upper.flip_h = sprite.flip_h
	upper.animation = "up%d" % move
	upper.frame = frame
	if is_on_floor():
		_play_synced("base_run")
		upper.position.y = RUN_HIP_OFFSET[sprite.frame % RUN_HIP_OFFSET.size()]
	else:
		sprite.play("base_rise" if velocity.y < 0.0 else "base_fall")

# Run and base_run share their timing: switching keeps the stride phase.
func _play_synced(animation_name: StringName) -> void:
	if sprite.animation == animation_name:
		sprite.play(animation_name)
		return
	var strides := [&"run", &"base_run", &"bow_run", &"knife_run"]
	var keep: bool = sprite.animation in strides and animation_name in strides
	var frame := sprite.frame
	var progress := sprite.frame_progress
	sprite.play(animation_name)
	if keep:
		sprite.set_frame_and_progress(frame, progress)

func _update_landing(fall_speed: float) -> void:
	var on_floor := is_on_floor()
	if on_floor and not was_on_floor and fall_speed >= LAND_SPEED:
		land_time = LAND_DURATION
		land_dusts.append([global_position, 0.0])
	was_on_floor = on_floor

func _age_sparks(delta: float) -> void:
	for spark in hit_sparks:
		spark[1] += delta
	hit_sparks = hit_sparks.filter(func(spark): return spark[1] < SPARK_DURATION)
	for dust in land_dusts:
		dust[1] += delta
	land_dusts = land_dusts.filter(func(dust): return dust[1] < LAND_DUST_DURATION)

func _strip_frame(texture: Texture2D, frames: int, index: int) -> Rect2:
	var w: float = texture.get_width() / float(frames)
	return Rect2(w * clampi(index, 0, frames - 1), 0, w, texture.get_height())

func _draw() -> void:
	if motion_state == MotionState.WALL_SLIDE:
		# Grit where the braced foot and the gripping hand scrape the wall.
		var dust_frame: int = (Engine.get_physics_frames() / 4) % 3
		for height in [-9.0, -27.0]:
			draw_texture_rect_region(DUST_TEXTURE, Rect2(Vector2(-wall_normal * 5.0 - 3.0, height), Vector2(6, 8)), _strip_frame(DUST_TEXTURE, 3, (dust_frame + int(height)) % 3))
	for dust in land_dusts:
		var land_frame: int = int(dust[1] / LAND_DUST_DURATION * 4.0)
		draw_texture_rect_region(LAND_DUST_TEXTURE, Rect2(to_local(dust[0]) - Vector2(16, 8), Vector2(32, 8)), _strip_frame(LAND_DUST_TEXTURE, 4, land_frame))
	if jump_flash > 0.0:
		var puff_frame: int = int((1.0 - jump_flash / 0.22) * 5.0)
		draw_texture_rect_region(PUFF_TEXTURE, Rect2(to_local(jump_effect_origin) - Vector2(12, 6), Vector2(24, 10)), _strip_frame(PUFF_TEXTURE, 5, puff_frame))
	for spark in hit_sparks:
		var spark_frame: int = int(spark[1] / SPARK_DURATION * 5.0)
		draw_texture_rect_region(SPARK_TEXTURE, Rect2(to_local(spark[0]) - Vector2(8, 8), Vector2(16, 16)), _strip_frame(SPARK_TEXTURE, 5, spark_frame))
