@tool
extends StaticBody2D

const DAMAGE = 0.5

func _physics_process(_delta: float) -> void:
	if Engine.is_editor_hint(): return
	for body in $Contact.get_overlapping_bodies():
		if body is SlicePlayer:
			var away := signf(to_local(body.global_position).x)
			if is_zero_approx(away): away = -body.facing
			var impulse := Vector2(away * 90.0, -180.0).rotated(global_rotation)
			body.take_damage(DAMAGE, impulse, SlicePlayer.DamageSource.SOLID_TRAP)

func _draw() -> void:
	# Generated by tools/art/hazards.py; origin at the bottom-centre of the base plate.
	draw_texture(preload("res://assets/sprites/trap_spikes.png"), Vector2(-16, -14))
