@tool
extends StaticBody2D

const DAMAGE = 0.5

func _physics_process(_delta: float) -> void:
	if Engine.is_editor_hint(): return
	for body in $Contact.get_overlapping_bodies():
		if body is SlicePlayer:
			var away := signf(to_local(body.global_position).x)
			if is_zero_approx(away): away = -body.facing
			var impulse := Vector2(away * 90.0, -180.0).rotated(global_rotation)
			body.take_damage(DAMAGE, impulse, SlicePlayer.DamageSource.SOLID_TRAP)

const ART = preload("res://assets/sprites/trap_spikes.png")
var shown_frame: int = -1

func _process(_delta: float) -> void:
	# A cold glint sweeps the tips every few seconds (6-frame strip, frame 0 is the resting state).
	var t := fposmod(Time.get_ticks_msec() / 1000.0 + position.x * 0.013, 3.0)
	var frame := 0 if t < 2.5 else mini(4, 1 + int((t - 2.5) / 0.12))
	if frame != shown_frame:
		shown_frame = frame
		queue_redraw()

func _draw() -> void:
	# Generated by tools/art/hazards.py; origin at the bottom-centre of the base plate.
	draw_texture_rect_region(ART, Rect2(-16, -14, 32, 14), Rect2(maxi(shown_frame, 0) * 32, 0, 32, 14))
